import {
  X,
  Mail,
  Lock,
  User,
  Menu,
  Home,
  Component,
  Heart,
  Eye,
  EyeClosed,
  MessageCircle,
  Moon,
  Sun,
  Search,
  Settings,
  Settings2,
  Bell,
  Check,
  ChevronsUpDown,
  ChevronDown,
  Calendar,
  Pen,
  Smile,
  AlertCircle,
  Aperture,
  Camera,
  CircleX,
  Construction,
  Fullscreen,
  GalleryThumbnails,
  ImageOff,
  ScanQrCode,
  Squircle,
  SwitchCamera,
  Zap,
  ZapOff,
  Plus
} from "lucide-react-native";

import { iconWithClassName } from "./iconWithClassName";
iconWithClassName(X);
iconWithClassName(Mail);
iconWithClassName(Lock);
iconWithClassName(User);
iconWithClassName(Menu);
iconWithClassName(Home);
iconWithClassName(Component);
iconWithClassName(Heart);
iconWithClassName(MessageCircle);
iconWithClassName(Moon);
iconWithClassName(Sun);
iconWithClassName(Search);
iconWithClassName(Settings);
iconWithClassName(Settings2);
iconWithClassName(Bell);
iconWithClassName(Check);
iconWithClassName(ChevronsUpDown);
iconWithClassName(ChevronDown);
iconWithClassName(Calendar);
iconWithClassName(Pen);
iconWithClassName(Smile);
iconWithClassName(GalleryThumbnails);
iconWithClassName(Squircle);
iconWithClassName(SwitchCamera);
iconWithClassName(Aperture);
iconWithClassName(Zap);
iconWithClassName(ZapOff);
iconWithClassName(Camera);
iconWithClassName(ScanQrCode);
iconWithClassName(Fullscreen);
iconWithClassName(CircleX);
iconWithClassName(Construction);
iconWithClassName(AlertCircle);
iconWithClassName(ImageOff);
iconWithClassName(Plus);
export {
  X,
  Mail,
  Lock,
  User,
  Menu,
  Home,
  Component,
  Heart,
  Eye,
  EyeClosed,
  MessageCircle,
  Moon,
  Sun,
  Search,
  Settings,
  Settings2,
  Bell,
  Check,
  ChevronsUpDown,
  ChevronDown,
  Calendar,
  Pen,
  Smile,
  AlertCircle,
  Aperture,
  Camera,
  CircleX,
  Construction,
  Fullscreen,
  GalleryThumbnails,
  ImageOff,
  ScanQrCode,
  Squircle,
  SwitchCamera,
  Zap,
  ZapOff,
  Plus
};
