import {
  X,
  Mail,
  Lock,
  User,
  Menu,
  Home,
  Component,
  Heart,
  Eye,
  EyeClosed,
  MessageCircle,
  Moon,
  Sun,
  Search,
  Settings,
  Settings2,
  Bell,
  Check,
  ChevronsUpDown,
  Calendar,
  Pen
} from "lucide-react-native";

import { iconWithClassName } from "./iconWithClassName";
iconWithClassName(X);
iconWithClassName(Mail);
iconWithClassName(Lock);
iconWithClassName(User);
iconWithClassName(Menu);
iconWithClassName(Home);
iconWithClassName(Component);
iconWithClassName(Heart);
iconWithClassName(MessageCircle);
iconWithClassName(Moon);
iconWithClassName(Sun);
iconWithClassName(Search);
iconWithClassName(Settings);
iconWithClassName(Settings2);
iconWithClassName(Bell);
iconWithClassName(Check);
iconWithClassName(ChevronsUpDown);
iconWithClassName(Calendar);
iconWithClassName(Pen);
export {
  X,
  Mail,
  Lock,
  User,
  Menu,
  Home,
  Component,
  Heart,
  Eye,
  EyeClosed,
  MessageCircle,
  Moon,
  Sun,
  Search,
  Settings,
  Settings2,
  Bell,
  Check,
  ChevronsUpDown,
  Calendar,
  Pen
};
